<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('orders')->insert([
            [
                'kode_order' => 'ORD001',
                'data_otlets_id' => 1,
                'stocks_id' => 1,
                'kode_salesman' => 'SLS001',
                'nama_salesman' => 'Salesman 1',
                'nama_barang' => 'Barang 1',
                'harga_dalam_kota' => '10000',
                'quantity' => '10',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD002',
                'data_otlets_id' => 2,
                'stocks_id' => 2,
                'kode_salesman' => 'SLS002',
                'nama_salesman' => 'Salesman 2',
                'nama_barang' => 'Barang 2',
                'harga_dalam_kota' => '20000',
                'quantity' => '20',
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD003',
                'data_otlets_id' => 3,
                'stocks_id' => 3,
                'kode_salesman' => 'SLS003',
                'nama_salesman' => 'Salesman 3',
                'nama_barang' => 'Barang 3',
                'harga_dalam_kota' => '30000',
                'quantity' => '30',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD004',
                'data_otlets_id' => 4,
                'stocks_id' => 4,
                'kode_salesman' => 'SLS004',
                'nama_salesman' => 'Salesman 4',
                'nama_barang' => 'Barang 4',
                'harga_dalam_kota' => '40000',
                'quantity' => '40',
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD005',
                'data_otlets_id' => 5,
                'stocks_id' => 5,
                'kode_salesman' => 'SLS005',
                'nama_salesman' => 'Salesman 5',
                'nama_barang' => 'Barang 5',
                'harga_dalam_kota' => '50000',
                'quantity' => '50',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD006',
                'data_otlets_id' => 6,
                'stocks_id' => 6,
                'kode_salesman' => 'SLS006',
                'nama_salesman' => 'Salesman 6',
                'nama_barang' => 'Barang 6',
                'harga_dalam_kota' => '60000',
                'quantity' => '60',
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD007',
                'data_otlets_id' => 7,
                'stocks_id' => 7,
                'kode_salesman' => 'SLS007',
                'nama_salesman' => 'Salesman 7',
                'nama_barang' => 'Barang 7',
                'harga_dalam_kota' => '70000',
                'quantity' => '70',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD008',
                'data_otlets_id' => 8,
                'stocks_id' => 8,
                'kode_salesman' => 'SLS008',
                'nama_salesman' => 'Salesman 8',
                'nama_barang' => 'Barang 8',
                'harga_dalam_kota' => '80000',
                'quantity' => '80',
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD009',
                'data_otlets_id' => 9,
                'stocks_id' => 9,
                'kode_salesman' => 'SLS009',
                'nama_salesman' => 'Salesman 9',
                'nama_barang' => 'Barang 9',
                'harga_dalam_kota' => '90000',
                'quantity' => '90',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD010',
                'data_otlets_id' => 10,
                'stocks_id' => 10,
                'kode_salesman' => 'SLS010',
                'nama_salesman' => 'Salesman 10',
                'nama_barang' => 'Barang 10',
                'harga_dalam_kota' => '100000',
                'quantity' => '100',
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_order' => 'ORD011',
                'data_otlets_id' => 11,
                'stocks_id' => 11,
                'kode_salesman' => 'SLS011',
                'nama_salesman' => 'Salesman 11',
                'nama_barang' => 'Barang 11',
                'harga_dalam_kota' => '110000',
                'quantity' => '110',
                'status' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
