<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SalePiutangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sale_piutangs')->insert([
            [
                'tanggal' => '2023-05-01',
                'nomor_nota' => 'INV12345',
                'kode_customer' => 'CUST001',
                'nama_customer' => 'John Doe',
                'daerah' => 'Jakarta',
                'tagihan' => 'Tagihan 1',
                'antaran' => 'Antaran 1',
                'umur' => 30,
                'kode_salesman' => 'SLS001',
                'nama_salesman' => 'Salesman 1',
                'total_nota' => 1000000.00,
                'sisa_hutang' => 500000.00,
                'sisa_hutang_by_sales' => 250000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-02',
                'nomor_nota' => 'INV12346',
                'kode_customer' => 'CUST002',
                'nama_customer' => 'Jane Smith',
                'daerah' => 'Bandung',
                'tagihan' => 'Tagihan 2',
                'antaran' => 'Antaran 2',
                'umur' => 45,
                'kode_salesman' => 'SLS002',
                'nama_salesman' => 'Salesman 2',
                'total_nota' => 1500000.00,
                'sisa_hutang' => 750000.00,
                'sisa_hutang_by_sales' => 375000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-03',
                'nomor_nota' => 'INV12347',
                'kode_customer' => 'CUST003',
                'nama_customer' => 'Mark Johnson',
                'daerah' => 'Surabaya',
                'tagihan' => 'Tagihan 3',
                'antaran' => 'Antaran 3',
                'umur' => 60,
                'kode_salesman' => 'SLS003',
                'nama_salesman' => 'Salesman 3',
                'total_nota' => 2000000.00,
                'sisa_hutang' => 1000000.00,
                'sisa_hutang_by_sales' => 500000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-04',
                'nomor_nota' => 'INV12348',
                'kode_customer' => 'CUST004',
                'nama_customer' => 'Emily Davis',
                'daerah' => 'Medan',
                'tagihan' => 'Tagihan 4',
                'antaran' => 'Antaran 4',
                'umur' => 75,
                'kode_salesman' => 'SLS004',
                'nama_salesman' => 'Salesman 4',
                'total_nota' => 2500000.00,
                'sisa_hutang' => 1250000.00,
                'sisa_hutang_by_sales' => 625000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-05',
                'nomor_nota' => 'INV12349',
                'kode_customer' => 'CUST005',
                'nama_customer' => 'Michael Wilson',
                'daerah' => 'Yogyakarta',
                'tagihan' => 'Tagihan 5',
                'antaran' => 'Antaran 5',
                'umur' => 90,
                'kode_salesman' => 'SLS005',
                'nama_salesman' => 'Salesman 5',
                'total_nota' => 3000000.00,
                'sisa_hutang' => 1500000.00,
                'sisa_hutang_by_sales' => 750000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-06',
                'nomor_nota' => 'INV12350',
                'kode_customer' => 'CUST006',
                'nama_customer' => 'Sophia Martinez',
                'daerah' => 'Semarang',
                'tagihan' => 'Tagihan 6',
                'antaran' => 'Antaran 6',
                'umur' => 105,
                'kode_salesman' => 'SLS006',
                'nama_salesman' => 'Salesman 6',
                'total_nota' => 3500000.00,
                'sisa_hutang' => 1750000.00,
                'sisa_hutang_by_sales' => 875000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-07',
                'nomor_nota' => 'INV12351',
                'kode_customer' => 'CUST007',
                'nama_customer' => 'Oliver Anderson',
                'daerah' => 'Malang',
                'tagihan' => 'Tagihan 7',
                'antaran' => 'Antaran 7',
                'umur' => 120,
                'kode_salesman' => 'SLS007',
                'nama_salesman' => 'Salesman 7',
                'total_nota' => 4000000.00,
                'sisa_hutang' => 2000000.00,
                'sisa_hutang_by_sales' => 1000000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-08',
                'nomor_nota' => 'INV12352',
                'kode_customer' => 'CUST008',
                'nama_customer' => 'Ava Taylor',
                'daerah' => 'Bali',
                'tagihan' => 'Tagihan 8',
                'antaran' => 'Antaran 8',
                'umur' => 135,
                'kode_salesman' => 'SLS008',
                'nama_salesman' => 'Salesman 8',
                'total_nota' => 4500000.00,
                'sisa_hutang' => 2250000.00,
                'sisa_hutang_by_sales' => 1125000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-09',
                'nomor_nota' => 'INV12353',
                'kode_customer' => 'CUST009',
                'nama_customer' => 'Mia Thomas',
                'daerah' => 'Palembang',
                'tagihan' => 'Tagihan 9',
                'antaran' => 'Antaran 9',
                'umur' => 150,
                'kode_salesman' => 'SLS009',
                'nama_salesman' => 'Salesman 9',
                'total_nota' => 5000000.00,
                'sisa_hutang' => 2500000.00,
                'sisa_hutang_by_sales' => 1250000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-10',
                'nomor_nota' => 'INV12354',
                'kode_customer' => 'CUST010',
                'nama_customer' => 'Liam Clark',
                'daerah' => 'Makassar',
                'tagihan' => 'Tagihan 10',
                'antaran' => 'Antaran 10',
                'umur' => 165,
                'kode_salesman' => 'SLS010',
                'nama_salesman' => 'Salesman 10',
                'total_nota' => 5500000.00,
                'sisa_hutang' => 2750000.00,
                'sisa_hutang_by_sales' => 1375000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tanggal' => '2023-05-11',
                'nomor_nota' => 'INV12355',
                'kode_customer' => 'CUST011',
                'nama_customer' => 'Noah Lewis',
                'daerah' => 'Surakarta',
                'tagihan' => 'Tagihan 11',
                'antaran' => 'Antaran 11',
                'umur' => 180,
                'kode_salesman' => 'SLS011',
                'nama_salesman' => 'Salesman 11',
                'total_nota' => 6000000.00,
                'sisa_hutang' => 3000000.00,
                'sisa_hutang_by_sales' => 1500000.00,
                'persentase_pemberian_barang' => '50%',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
